### ISSUE TITLE
add onAnimationStartEvent 

### ISSUE THREAD

**Issue by jkozniewski** [Whitebrim/AnimatedSprite#8]
Hi - maybe I'm wrong but there seems to be no event called when animation starts ? 
In my case that would be quite handy as I'm animating a muzzle flash which should disappear  from the screen when animation ends (basically using `setVisible(false)` method of a sprite class.

It looks like this (thought that maybe `onStateChangedEvent` is gonna be called after each `playAnimation()` but apparently not:
```lua
local bang = gfx.imagetable.new( "images/fx/muzzleFlash1_01" )
self.bangAnim = AnimatedSprite.new( bang )
self.bangAnim.states.default.onAnimationEndEvent = function (self) self:setVisible(false) end
-- unfortunately  not called after each playAnimation() call:
-- self.bangAnim.states.default.onStateChangedEvent = function (self) self:setVisible(true) end

-- something like this would be helpful:
-- self.bangAnim.states.default.onAnimationStartEvent = function (self) self:setVisible(true) end
end
```
Or am I missing some other obvious way of achieving this "one-shot" (pun intended) animations that do not stuck at displaying last frame when animation is finished ?

**Comment by Whitebrim** [comment]
![image](https://user-images.githubusercontent.com/23287829/217839931-53cfcfa2-94ae-4f8f-b947-985a11678767.png)


Default state has loop set to `true`, so it basically never ends.
Try `self.bangAnim.states.default.loop = false`

I think onAnimationStartEvent in unnesesary extra load for the class because it'll try to call every time someone is starting animation. You can just start animation and do whatever you want to do on animation start right away on the next line. If you're going to start animation many times from different places, you can create function that will start animation and next line will do what you want.

I suggest not everriding default state but creating your own state for better understanding what's going on:

```lua
local bang = gfx.imagetable.new( "images/fx/muzzleFlash1_01" )
self.bangAnim = AnimatedSprite.new( bang )
self.bangAnim:addState("bang", nil, nil, {loop = false, onAnimationEndEvent = function (self) self:setVisible(false) end})
self.bangAnim:setVisible(true)
self.bangAnim:playAnimation()
```

**Comment by Whitebrim** [comment]
@jkozniewski Is it fixed for you?
